// Generated by gencpp from file imu_driver/Mile.msg
// DO NOT EDIT!


#ifndef IMU_DRIVER_MESSAGE_MILE_H
#define IMU_DRIVER_MESSAGE_MILE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace imu_driver
{
template <class ContainerAllocator>
struct Mile_
{
  typedef Mile_<ContainerAllocator> Type;

  Mile_()
    : leftPulse(0)
    , rightPulse(0)  {
    }
  Mile_(const ContainerAllocator& _alloc)
    : leftPulse(0)
    , rightPulse(0)  {
  (void)_alloc;
    }



   typedef int32_t _leftPulse_type;
  _leftPulse_type leftPulse;

   typedef int32_t _rightPulse_type;
  _rightPulse_type rightPulse;




  typedef boost::shared_ptr< ::imu_driver::Mile_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_driver::Mile_<ContainerAllocator> const> ConstPtr;

}; // struct Mile_

typedef ::imu_driver::Mile_<std::allocator<void> > Mile;

typedef boost::shared_ptr< ::imu_driver::Mile > MilePtr;
typedef boost::shared_ptr< ::imu_driver::Mile const> MileConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_driver::Mile_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_driver::Mile_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace imu_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'imu_driver': ['/home/cxf/catkin_ws/src/imu_driver/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::imu_driver::Mile_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_driver::Mile_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_driver::Mile_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_driver::Mile_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_driver::Mile_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_driver::Mile_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_driver::Mile_<ContainerAllocator> >
{
  static const char* value()
  {
    return "464c6b59a02768a6ec1bb52d089c2ce1";
  }

  static const char* value(const ::imu_driver::Mile_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x464c6b59a02768a6ULL;
  static const uint64_t static_value2 = 0xec1bb52d089c2ce1ULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_driver::Mile_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_driver/Mile";
  }

  static const char* value(const ::imu_driver::Mile_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_driver::Mile_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 leftPulse\n\
int32 rightPulse\n\
";
  }

  static const char* value(const ::imu_driver::Mile_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_driver::Mile_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.leftPulse);
      stream.next(m.rightPulse);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Mile_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_driver::Mile_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_driver::Mile_<ContainerAllocator>& v)
  {
    s << indent << "leftPulse: ";
    Printer<int32_t>::stream(s, indent + "  ", v.leftPulse);
    s << indent << "rightPulse: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rightPulse);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_DRIVER_MESSAGE_MILE_H
